### ISSUE TITLE
Feature request: Levi-civita symbol ε for expressions

### ISSUE THREAD

**Issue by VikingScientist** [evalf/nutils#289]
Seeing as you're already supporting greek letters and the kronecker delta, I figured it would only make sense to also support the [Levi-Civita](https://en.wikipedia.org/wiki/Levi-Civita_symbol) symbol.

**Comment by joostvanzwieten** [comment]
Commit cb1ec46d adds `function.levicivita`. You should add one of the correct dimension to the namespace yourself, e.g.

```python
ns.ε = function.levicivita(3)
```
