### ISSUE TITLE
topology.basis('discont', degree=0) error

### ISSUE THREAD

**Issue by amalikmichael** [evalf/nutils#468]
burgers.py in the examples of the latest master branch fails to run with degree=0 (otherwise, it runs normally) and returns the following assertion error

File "~/nutils/nutils/function.py", line 973, in simplified
    assert retval.shape == self.shape
AssertionError

Might be something wrong in the simplification step in this case because when I replace func = self.func.simplified with func = self.func in line 969, everything works again.

**Comment by gertjanvanzwieten** [comment]
I opened #427 to take care of this issue. @amalikmichael and @daanvdwoude could you see if this solves the problem for your use case?

**Comment by joostvanzwieten** [comment]
Fixed by #427
