### ISSUE TITLE
Flag to override Windows defaulting to int32

### ISSUE THREAD

**Issue by jeffrey-cochran** [evalf/nutils#550]
I got an integer overflow that was not reproducible on my colleague's machine when assigning size in [parallel.shempty](https://github.com/evalf/nutils/blob/862aa5137fc84f3e4f69f52c4d3301aceba4f662/nutils/parallel.py#L101)

It seems very likely that this is because 64bit Windows defaults to int32 for compatibility reasons, and my colleague is on 64bit Linux, which defaults to int64. 

It would be nice if I had a quick way to force nutils to use int64 for consistency's sake. 

See [this post](https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine)

**Comment by gertjanvanzwieten** [comment]
Is this in Nutils master? Because since #531 (merged April 25) the dtype for matrix assembly is determined based on the size of the integrand, precisely so that overflows should not occur. Can you describe how the problem manifests exactly?

**Comment by jeffrey-cochran** [comment]
This is not in nutils master. This is PyPI v6.0. 

I am not calling it directly. 

Let me look at the relevant code in master branch real quick

**Comment by jeffrey-cochran** [comment]
PS I'm pretty sure this is why Mike Johnson was getting a negative dimension error: https://matrix.to/#/!LDzDHBATBUDFaEenky:delft.diskos.nl/$158882776063553iKJFi:matrix.org?via=delft.diskos.nl&via=matrix.org

I think it's being caused by integer overflow. I'll try running his script locally.

**Comment by gertjanvanzwieten** [comment]
Ah I see, that explains, and indeed that last test confirms it. Thanks for the digging! I'll create a PR with the proposed fix and a bounds check to make sure this does not happen again.

**Comment by gertjanvanzwieten** [comment]
@jeffrey-cochran could you confirm that #551 fixes this issue?

**Comment by jeffrey-cochran** [comment]
I just checked out that branch, installed via setup.py on a new conda environment, and ran Mike Johnson's file again. I didn't run it to completion (with my machine that would take forever), but I didn't get the negative dimension error before the matrices took up all 32GB of my memory, so I think it fixed it

**Comment by gertjanvanzwieten** [comment]
Great, thanks for checking. We will merge #551 later today then.
