### ISSUE TITLE
Inconsistent NumPy version requirement

### ISSUE THREAD

**Issue by MakisH** [evalf/nutils#577]
I was looking for the NumPy requirement of nutils, which on [setup.py](https://github.com/evalf/nutils/blob/8bc8f9b052558cf611284b904ce2bb24ec7df365/setup.py) is 1.12:

https://github.com/evalf/nutils/blob/8bc8f9b052558cf611284b904ce2bb24ec7df365/setup.py#L38

However, at runtime, nutils requires 1.15:

https://github.com/evalf/nutils/blob/8bc8f9b052558cf611284b904ce2bb24ec7df365/nutils/__init__.py#L25

It would be better to make the two requirements consistent, to avoid surprises.

**Comment by joostvanzwieten** [comment]
This is fixed in master. Thanks for reporting.
