### ISSUE TITLE
WSL in README.md

### ISSUE THREAD

**Issue by timovanopstal** [evalf/nutils#670]
I understand WSL is the way to go for using Nutils in a Windows environment (I wasn't aware.) Does it make sense to elaborate on this in the readme?

**Comment by joostvanzwieten** [comment]
If you want to assemble matrices in parallel, then WSL is the way to go. Docker, which (nowadays?) uses WSL2 as well, is an option for production code.

We don't have a Windows machine (yet), so we can't write step-by-step instructions ourselves. We'd appreciate contributions to the readme from anyone with experience.

**Comment by scdivi** [comment]
I have been using WSL (without parallel). In my experience, the only step we need in README.md is an instruction to setup WSL environment. After setting it up, the existing steps under installation in README.md can be used to setup nutils. I will propose a change to README.md.
