### ISSUE TITLE
Written and printed directories of log file in the WSL setup

### ISSUE THREAD

**Issue by scdivi** [evalf/nutils#671]
Accessing log file generated by Nutils in the WSL setup is very inconvenient with the current setup. One of the aspects of the WSL is that it writes the log file to a directory according to ubuntu directory. For example, if my public_html location is `/mnt/c/User/username/public_html`. The log file is saved in this directory and the same url (with file:// appending in front) and it is also printing in the log (on the terminal). However, this url cannot be accessed via browser because browser knows the direction according to the windows url. For example: `/C:/Users/username/public_html`. So the written directory and the printed directory should different for the WSL setup. Can this be implemented in cli.py?

**Comment by joostvanzwieten** [comment]
You can either add `outrooturi='file:///C:/Users/username/public_html/'` to your Nutils config file (`$HOME/.config/nutils/config` in Linux) or [set environment variable](https://stackoverflow.com/a/65258772) `NUTILS_OUTROOTURI` to `file:///C:/Users/username/public_html/`.
