### ISSUE TITLE
Error in running the examples

### ISSUE THREAD

**Issue by tengzhang48** [evalf/nutils#731]
Hello,

I am new to nutils and just installed it through pip. I can run the python tests but have the following error when trying to run the examples
"AttributeError: 'Namespace' object has no attribute 'add_field'"

I tested "laplace.py" and "elasticity.py" and found the same error. Could you please help me take a look?

Thanks.

Best,
Teng

**Comment by tengzhang48** [comment]
I just realized that I did not install the most recent version. I update the installation and can run the simulations. I think the simulations are completed but got another error this time
"finish 2022-11-19 17:39:09, elapsed 0:00
ModuleNotFoundError: No module named 'cycler'"

But I did not find a command in the script to call this module. Could you please help me check this error?

Thanks.

**Comment by tengzhang48** [comment]
I updated matplotlib and can successfully run the examples.

**Comment by joostvanzwieten** [comment]
On [PyPI](https://pypi.org/project/nutils/) (the default package repository for `pip`) you can find the latest stable version of Nutils (currently 7.2). If you want to try out one of the examples, you should download the version of the example that corresponds to the installed version of Nutils. You can find the examples for version 7 [here](https://github.com/evalf/nutils/tree/release/7/examples) and a subset on our [examples website](https://examples.nutils.org).

Based on the error message you've posted above and the way you've resolved the problem, I assume that you've installed the development version of Nutils. Unless you need features that are not present in the stable version, I suggest to revert to Nutils stable (`pip install --upgrade nutils==7`) and download the accompanying examples.

We try to keep Nutils as backwards compatible as possible, so examples for version 7 typically work with the development version of Nutils as well. As you have encountered already, the converse is not true.
